logging:
  config: classpath:logback.xml
  path: C:/logs
  level: 
    org: 
      springframework: 
         security: INFO
         


management: 
  endpoints: 
    web: 
      expose: /
server:
  port: 8081
  context-path: /
  session-timeout: 60
  cloudAddress: 119.29.215.46
     
security:
  user:
    name: momo
    password: 123
  basic:
    enabled: false
mybatis:
     mapperLocations: classpath:/cn/momosv/mybatis/dao/*.xml
     typeAliasesPackage: cn.momosv.mybatis.dao    
     mapperScanPackage: cn.momosv.mybatis.dao
     configLocation: classpath:/mybatis-config.xml

spring:
    datasource:
        name: db      
        url: jdbc:mysql://119.29.215.46:3306/softdesign?useSSL=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true
        username: momo
        password: ****
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        minIdle: 5
        maxActive: 100
        initialSize: 10
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        removeAbandoned: true
        filters: stat  
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录  
        useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据  
        druidLoginName: wjf # 登录druid的账号  
        druidPassword: wjf # 登录druid的密码    
     # HTTP ENCODING  
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true  
    thymeleaf: 
      cache: false
    freemarker:   
        allow-request-override: false  
        allow-session-override: false  
        cache: true  
        check-template-location: true  
        content-type: text/html  
        enabled: true  
        expose-request-attributes: false  
        expose-session-attributes: false  
        expose-spring-macro-helpers: true  
        prefer-file-system-access: true  
        suffix: .html
        template-loader-path: classpath:/templates
        settings:
          template_update_delay: 0  
          default_encoding: UTF-8  
          classic_compatible: true  
      #    order: 1    
    jpa:
      hibernate:
       ddl-auto: update
      show-sql: true      
#邮件
    mail:  
      host: smtp.exmail.qq.com
      username: momosv@momosv.cn
      password: ***
      properties:  
        mail: 
          self: 
            username: momo 
          smtp:  
            socketFactory: 
              class: javax.net.ssl.SSLSocketFactory  
              port: 465  
            auth: true  
            starttls:  
              enable: true  
              required: true   